# Q1


In [5]:
import numpy as np
a=np.array([1,5,9,26,20])
print("first array",a)
X=a.tolist()
print(X)


first array [ 1  5  9 26 20]
[1, 5, 9, 26, 20]


# Q2


In [16]:
import numpy as np
A=np.array([[0,3,4],[2,7,1],[8,9,5]])
print(A)
sum=lambda a,b,c:a+b+c
a=A[0][0]
b=A[1][1]
c=A[2][2]
print (sum(a,b,c))
a=A[2][0]
b=A[1][1]
c=A[0][2]
print (sum(a,b,c))

[[0 3 4]
 [2 7 1]
 [8 9 5]]
12
19


# Q3




In [27]:
import numpy as np
a = np.array([[1,2],[3,5]])
my_list=[]
x=4
if x<a[0][0]:
    my_list.append(a[0][0])
elif x<a[0][1]:
    my_list.append (a[0][1])
elif x<a[1][0]:
    my_list.append (a[1][0])
elif x<a[1][1]:
    my_list.append (a[1][1])
print(my_list)

[5]


# Q4

In [29]:
import numpy as np
A=np.array([3,7,9])
B=np.array([2,5,7])
C=A+B
print(C)

[ 5 12 16]


# Q5

In [36]:
import numpy as np
A=np.array([[2,8,9],[10,22,3],[0,3,6]])
m1=(A[0][0]+A[1][0]+A[2][0])/3
m2=(A[0][1]+A[1][1]+A[2][1])/3
m3=(A[0][2]+A[1][2]+A[2][2])/3
print("the mean of first raw is",m1,"and the mean of second raw is",m2,"and the mean of last raw is",m3)

the mean of first raw is 4.0 and the mean of second raw is 11.0 and the mean of last raw is 6.0
